global:
  backgrounds_dir: output/backgrounds
  output_dir: output
  dataset_dir: dataset
  training_mode: per_component
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  components_per_img_min: 1
  components_per_img_max: 3
  allow_random_rotation: true
  require_full_visibility: true
  sprite_scale_min: 0.07
  sprite_scale_max: 0.15
  negative_ratio: 0.2
  binarize_threshold: 200
  render_dpi: 200
  yolo_workspace: yolo_workspace
  yolo_model: yolo11s.pt
  epochs: 300
  patience: 100
  batch_size: 16
  workers: 0
  imgsz: 640
  epochs_finetune: 100
  lr0: 0.001
  lr0_finetune: 0.001
  lrf_finetune: 0.001
  project: Liard_Detection
backgrounds:
  enabled: false
  dxf_sources_dir: input/backgrounds
  render_dpi: 4098
  tile_size: 640
  overlap: 320
  min_std_dev: 10
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 2.0
  perspective: 0.0
  flipud: 0.1
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.15
  copy_paste: 0.1
  erasing: 0.4
modifiers:
  dir: input/modifiers
  probability: 0.95
  count_min: 1
  count_max: 5
  allow_rotation: true
  thickness_dilation:
  - 1
  - 3
validation:
  max_missing_labels_pct: 5.0
components:
- name: ojo_de_buey
  dxf_path:
  - input/components/ojo_de_buey.dxf
  roboflow_zip_path: ../zips_datasets/Ojo_de_buey.yolov11.zip
  images_to_generate: 5000
  line_thickness_range:
  - 10
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 90

- name: grupo_electrogeno
  dxf_path:
  - input/components/grupo_electrogeno.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: celda_media_tension
  dxf_path:
  - input/components/celda_media_tension.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: bornera
  dxf_path:
  - input/components/bornera.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: interruptor_temporizado
  dxf_path:
  - input/components/interruptor_temporizado.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: interruptor_motorizado
  dxf_path:
  - input/components/interruptor_motorizado.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: puesta_a_tierra
  dxf_path:
  - input/components/puesta_a_tierra.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: transformador
  dxf_path:
  - input/components/transformador.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: seccionador_con_contactor
  dxf_path:
  - input/components/seccionador_con_contactor.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

- name: seccionador_bajo_carga_con_fusible
  dxf_path:
  - input/components/seccionador_bajo_carga_con_fusible.dxf
  images_to_generate: 300
  line_thickness_range:
  - 5
  - 50
  polarity_filters:
  - invert
  - threshold
  sprite_variations: 20
  skip_training: true

